function create(obj)
% create - Creates all parts of the viewer display
% -------------------------------------------------------------------------
%
% Notes: none
%

%   Copyright 2018-2019 The MathWorks Inc.
%
% Auth/Revision:
%   MathWorks Consulting
%   $Author: rjackey $
%   $Revision: 324 $  $Date: 2019-04-23 08:05:17 -0400 (Tue, 23 Apr 2019) $
% ---------------------------------------------------------------------


%% Create a menu

obj.Menu.Data.Menu = uimenu(...
    'Parent',obj.Figure,...
    'Label','Data',...
    'Tag','FileMenu');

obj.Menu.Data.Load = uimenu(...
    'Parent',obj.Menu.Data.Menu,...
    'Label','Load Data (airlinesmall.csv)',...
    'Tag','DataLoad',...
    'Callback',@(h,e)onDataMenuItem(obj,e));


%% Create the layout

obj.hLayout.MainH = uix.HBoxFlex(...
    'Parent',obj.Figure,...
    'Padding',4,...
    'Spacing',8);

obj.hLayout.LeftV = uix.VBox(...
    'Parent',obj.hLayout.MainH,...
    'Padding',0,...
    'Spacing',8);


%% Create the main components

obj.h.BarChart = demoAppPkg.view.BarChart(...
    'Parent',obj.hLayout.MainH,...
    'DataModel',obj.Session);

obj.h.PlotSelector = demoAppPkg.view.PlotSelector(...
    'Parent',obj.hLayout.LeftV,...
    'DataModel',obj.Session);

obj.h.DisplayTable = demoAppPkg.view.DisplayTable(...
    'Parent',obj.hLayout.LeftV,...
    'DataModel',obj.Session);


%% Adjust sizes

obj.hLayout.MainH.Widths = [-1 -1];
obj.hLayout.LeftV.Heights = [150 -1];
