function [scaling_xyz] = affine_translation(x_scaler, y_scaler, z_scaler)


scaling_xyz =   [ x_scaler, 0, 0, 0;...
                  0, y_scaler, 0, 0;...
                  0, 0, z_scaler, 0;...
                  0, 0, 0, 1];
                   