function [rotate_x, rotate_y, rotate_z] = affine_rotation(alpha_x, alpha_y, alpha_z)


rotate_x = [            1,            0,             0, 0;...
                        0, cos(alpha_x), -sin(alpha_x), 0;...
                        0, sin(alpha_x),  cos(alpha_x), 0;...
                        0,            0,             0, 1];
                   
                   
rotate_y = [ cos(alpha_y),            0,  sin(alpha_y), 0;...
                        0,            1,             0, 0;...
            -sin(alpha_y),            0,  cos(alpha_y), 0;...
                        0,            0,             0, 1];


rotate_z = [ cos(alpha_z),-sin(alpha_z),             0, 0;...
             sin(alpha_z), cos(alpha_z),             0, 0;...
                        0,            0,             1, 0;...
                        0,            0,             0, 1];